name: infra
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
description: this project manages core infrastructure items
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
